name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache build artifacts
        uses: actions/cache@v2
        env:
          cache-name: build-cache
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - uses: bazelbuild/setup-bazelisk@v1

      - name: Run Go version
        run: go version

      - name: Check gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Run bazel version
        run: bazel --version

      - name: Check generated code
        run: | # skip over swig, proto, and go files to bound image size and build times
          make bzl
          git diff --exit-code

      - name: Run tests
        run: |
          make test
